version: "3"

services:
  hotel-api:
    build:
      context: ./hotel-api
    env_file:
      - ./.env
    environment:
      - TRACING_URL=http://tracing:14268/api/traces

  weather-api:
    build:
      context: ./weather-api
    env_file:
      - ./.env
    environment:
      - TRACING_URL=http://tracing:14268/api/traces

  reservation-api:
    build:
      context: ./reservation-api
    env_file:
      - ./.env
    environment:
      - HOTELS_URL=http://hotel-api:8081/v1/hotels?city=
      - WEATHER_URL=http://weather-api:8082/v1/weather?city=
      - TRACING_URL=http://tracing:14268/api/traces
    ports:
      - "0.0.0.0:8080:8080"

  tracing:
    image: jaegertracing/all-in-one:latest
    ports:
      - "0.0.0.0:16686:16686"

